server:
  port: 8080

gemini:
  # ????????? API KEY
  api-key: "AIzaSyCkyRa5ntLeOxUiDih0fMcvnmsuB6xojQY"
  # ???? Clash ????
  proxy-host: "127.0.0.1"
  proxy-port: 7897

spring:
  datasource:
    # ?? 3306 ???????cyber_tutor ???????????
    url: jdbc:mysql://localhost:3306/cyber_tutor?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    # ??????????
    username: root
    password: 12345  # ?? ?????? MySQL ???
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # ???????
    show-sql: true # ?????? SQL ???????